# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: acquisition.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'acquisition.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61\x63quisition.proto\"\x10\n\x0e\x41\x63quireRequest\"/\n\x0f\x41\x63quireResponse\x12\r\n\x05label\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\x0c\"\x11\n\x0f\x44isplayResponse\".\n\x0e\x44isplayRequest\x12\r\n\x05label\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\x0c\x32p\n\x12\x41\x63quisitionService\x12,\n\x07\x61\x63quire\x12\x0f.AcquireRequest\x1a\x10.AcquireResponse\x12,\n\x07\x64isplay\x12\x0f.DisplayRequest\x1a\x10.DisplayResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'acquisition_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACQUIREREQUEST']._serialized_start=21
  _globals['_ACQUIREREQUEST']._serialized_end=37
  _globals['_ACQUIRERESPONSE']._serialized_start=39
  _globals['_ACQUIRERESPONSE']._serialized_end=86
  _globals['_DISPLAYRESPONSE']._serialized_start=88
  _globals['_DISPLAYRESPONSE']._serialized_end=105
  _globals['_DISPLAYREQUEST']._serialized_start=107
  _globals['_DISPLAYREQUEST']._serialized_end=153
  _globals['_ACQUISITIONSERVICE']._serialized_start=155
  _globals['_ACQUISITIONSERVICE']._serialized_end=267
# @@protoc_insertion_point(module_scope)
