kind: pipeline
spec:
  name: Yolo
---
kind: stage
spec:
  name: Yolodetect
  method: Detect 
  address: yologpt:8061
  pipeline: Yolo
---
kind: stage
spec: 
  name: gradio-source
  service: AcquisitionService
  method: acquire
  address: interface:8061
  pipeline: Yolo
---
kind: stage
spec: 
  name: gradio-display
  service: DisplayService
  method: display
  address: interface:8161
  pipeline: Yolo
---
kind: link
spec:
  name: yolo-gradio
  source_stage: Yolodetect
  target_stage: gradio-display
  pipeline: Yolo
---
kind: link
spec:
  name: gradio-yolo
  source_stage: gradio-source
  target_stage: Yolodetect
  pipeline: Yolo
