version: '3'
services:
  interface:
    image: sipgisr/acquisition
    ports:
    - 7860:7860
  yologpt:
    image: sipgisr/yolov11
  maestro:
    image: duartemralves/maestro:v1-latest
    volumes:
      - type: bind
        source: ./config.yaml
        target: /config.yaml
