services:
  interface:
    image: sipgisr/jupyterdev
    ports:
    - 7860:7860
    - 8888:8888
    volumes:
      - type: bind
        source: /home/jpc/aisp/boxes
        target: /home/jovyan/work/workspace
  yologpt:
    image: sipgisr/yolov11
    ports:
    - 8062:8061
  maestro:
    image: duartemralves/maestro:v1-latest
    volumes:
      - type: bind
        source: ./config.yaml
        target: /config.yaml
