version: '3'
services:
  interface:
    image: sipgisr/acquisition
    ports:
    - 7860:7860
    - 8061:8061    
    - 8161:8161
  yologpt:
    image: sipgisr/yolov11
    ports:
    - 8062:8061
  maestro:
    image: duartemralves/maestro:v1-latest
    volumes:
      - type: bind
        source: ./config.yaml
        target: /config.yaml
