# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: yolo.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'yolo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nyolo.proto\x12\x04yolo\":\n\x0bYOLORequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x1c\n\x14\x63onfidence_threshold\x18\x02 \x01(\x02\">\n\x0cYOLOResponse\x12\x15\n\rlabeled_image\x18\x01 \x01(\x0c\x12\x17\n\x0f\x64\x65tections_json\x18\x02 \x01(\t2>\n\x0bYOLOservice\x12/\n\x06\x44\x65tect\x12\x11.yolo.YOLORequest\x1a\x12.yolo.YOLOResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yolo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_YOLOREQUEST']._serialized_start=20
  _globals['_YOLOREQUEST']._serialized_end=78
  _globals['_YOLORESPONSE']._serialized_start=80
  _globals['_YOLORESPONSE']._serialized_end=142
  _globals['_YOLOSERVICE']._serialized_start=144
  _globals['_YOLOSERVICE']._serialized_end=206
# @@protoc_insertion_point(module_scope)
