# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: yolo.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'yolo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nyolo.proto\x12\x04yolo\"H\n\rYOLOGradioSeq\x12\x18\n\x10yolo_config_json\x18\x01 \x01(\t\x12\x0e\n\x06images\x18\x02 \x03(\x0c\x12\r\n\x05video\x18\x03 \x01(\x0c\x32\xbf\x01\n\x0bYOLOservice\x12\x39\n\rTrackSequence\x12\x13.yolo.YOLOGradioSeq\x1a\x13.yolo.YOLOGradioSeq\x12:\n\x0e\x44\x65tectSequence\x12\x13.yolo.YOLOGradioSeq\x1a\x13.yolo.YOLOGradioSeq\x12\x39\n\rAllProcessing\x12\x13.yolo.YOLOGradioSeq\x1a\x13.yolo.YOLOGradioSeqb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yolo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_YOLOGRADIOSEQ']._serialized_start=20
  _globals['_YOLOGRADIOSEQ']._serialized_end=92
  _globals['_YOLOSERVICE']._serialized_start=95
  _globals['_YOLOSERVICE']._serialized_end=286
# @@protoc_insertion_point(module_scope)
