# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: display.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'display.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdisplay.proto\"\x10\n\x0e\x41\x63quireRequest\"/\n\x0f\x41\x63quireResponse\x12\r\n\x05label\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x03(\x0c\".\n\x0e\x44isplayRequest\x12\r\n\x05label\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x03(\x0c\"\x11\n\x0f\x44isplayResponse2l\n\x0e\x44isplayService\x12,\n\x07\x64isplay\x12\x0f.DisplayRequest\x1a\x10.DisplayResponse\x12,\n\x07\x61\x63quire\x12\x0f.AcquireRequest\x1a\x10.AcquireResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'display_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACQUIREREQUEST']._serialized_start=17
  _globals['_ACQUIREREQUEST']._serialized_end=33
  _globals['_ACQUIRERESPONSE']._serialized_start=35
  _globals['_ACQUIRERESPONSE']._serialized_end=82
  _globals['_DISPLAYREQUEST']._serialized_start=84
  _globals['_DISPLAYREQUEST']._serialized_end=130
  _globals['_DISPLAYRESPONSE']._serialized_start=132
  _globals['_DISPLAYRESPONSE']._serialized_end=149
  _globals['_DISPLAYSERVICE']._serialized_start=151
  _globals['_DISPLAYSERVICE']._serialized_end=259
# @@protoc_insertion_point(module_scope)
