# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import display_pb2 as display__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in display_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DisplayServiceStub(object):
    """python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. display.proto

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.display = channel.unary_unary(
                '/DisplayService/display',
                request_serializer=display__pb2.DisplayRequest.SerializeToString,
                response_deserializer=display__pb2.DisplayResponse.FromString,
                _registered_method=True)
        self.acquire = channel.unary_unary(
                '/DisplayService/acquire',
                request_serializer=display__pb2.AcquireRequest.SerializeToString,
                response_deserializer=display__pb2.AcquireResponse.FromString,
                _registered_method=True)


class DisplayServiceServicer(object):
    """python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. display.proto

    """

    def display(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def acquire(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DisplayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'display': grpc.unary_unary_rpc_method_handler(
                    servicer.display,
                    request_deserializer=display__pb2.DisplayRequest.FromString,
                    response_serializer=display__pb2.DisplayResponse.SerializeToString,
            ),
            'acquire': grpc.unary_unary_rpc_method_handler(
                    servicer.acquire,
                    request_deserializer=display__pb2.AcquireRequest.FromString,
                    response_serializer=display__pb2.AcquireResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DisplayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DisplayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DisplayService(object):
    """python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. display.proto

    """

    @staticmethod
    def display(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DisplayService/display',
            display__pb2.DisplayRequest.SerializeToString,
            display__pb2.DisplayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def acquire(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DisplayService/acquire',
            display__pb2.AcquireRequest.SerializeToString,
            display__pb2.AcquireResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
