# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: simplebox.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'simplebox.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsimplebox.proto\"\x17\n\x07matfile\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\x31\n\x10SimpleBoxService\x12\x1d\n\x07process\x12\x08.matfile\x1a\x08.matfileb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'simplebox_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MATFILE']._serialized_start=19
  _globals['_MATFILE']._serialized_end=42
  _globals['_SIMPLEBOXSERVICE']._serialized_start=44
  _globals['_SIMPLEBOXSERVICE']._serialized_end=93
# @@protoc_insertion_point(module_scope)
