kind: pipeline
spec:
  name: full_gradio
---
kind: stage
spec:
  name: vggtgrpc
  method: Process
  address: vggtgrpc:8061
  pipeline: full_gradio
---
kind: stage
spec:
  name: yologrpc
  method: AllProcessing
  address: yologrpc:8061
  pipeline: full_gradio
---
kind: stage
spec: 
  name: gradio-acquire
  method: acquire
  address: interface:8061
  pipeline: full_gradio
---
kind: stage
spec: 
  name: gradio-display_yolo
  method: display_yolo
  address: interface:8061
  pipeline: full_gradio
---
kind: stage
spec: 
  name: gradio-display_vggt
  method: display_vggt
  address: interface:8061
  pipeline: full_gradio
---
kind: link
spec:
  name: gradio-vggt
  source_stage: gradio-acquire
  target_stage: vggtgrpc
  pipeline: full_gradio
---
kind: link
spec:
  name: gradio-yolo
  source_stage: gradio-acquire
  target_stage: yologrpc
  pipeline: full_gradio
---
kind: link
spec:
  name: yolo-gradio
  source_stage: yologrpc
  target_stage: gradio-display_yolo
  pipeline: full_gradio
---
kind: link
spec:
  name: vggt-gradio
  source_stage: vggtgrpc
  target_stage: gradio-display_vggt
  pipeline: full_gradio
