services:
  interface:
    image: sipgisr/displaygrpc
    ports:
      - 7861:7860   # Only expose if you want access from host
    networks:
      - mynet
  vggtgrpc:
    image: sipgisr/vggtgrpc
    networks:
      - mynet
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
  yologrpc:
    image: sipgisr/yologrpc
    networks:
      - mynet
  maestro:
    image: sipgisr/maestro:v1-latest
    volumes:
      - type: bind
        source: ./config.yaml
        target: /config.yaml
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
