kind: pipeline
spec:
  name: architecture_pipeline
---
kind: stage
spec:
  name: opencvgrpc
  method: similarity_check
  address: opencvgrpc:8061
  pipeline: architecture_pipeline
---
kind: stage
spec: 
  name: display_langsam
  method: display_langsam
  address: folder_wdgrpc:8061
  pipeline: architecture_pipeline
---
kind: stage
spec:
  name: acquire
  method: acquire
  address: folder_wdgrpc:8061
  pipeline: architecture_pipeline
---
kind: stage
spec:
  name: lang_sam
  method: Process
  address: lang_samgrpc:8061
  pipeline: architecture_pipeline
---
kind: stage
spec:
  name: yolo
  method: TrackSequence
  address: yologrpc:8061
  pipeline: architecture_pipeline
---
kind: stage
spec:
  name: display_yolo
  method: display_yolo
  address: folder_wdgrpc:8061
  pipeline: architecture_pipeline
---
kind: stage
spec:
  name: display_vggt
  method: display_vggt
  address: folder_wdgrpc:8061
  pipeline: architecture_pipeline
---
kind: stage
spec:
  name: acquire_vggt
  method: acquire_vggt
  address: folder_wdgrpc:8061
  pipeline: architecture_pipeline
---
kind: stage
spec:
  name: vggtgrpc
  method: Process
  address: vggtgrpc:8061
  pipeline: architecture_pipeline
---
kind: link
spec:
  name: acquire-opencv
  source_stage: acquire
  target_stage: opencvgrpc
  pipeline: architecture_pipeline
---
kind: link
spec:
  name: opencv-yolo
  source_stage: opencvgrpc
  target_stage: yolo
  pipeline: architecture_pipeline
---
kind: link
spec:
  name: opencv-lang_sam
  source_stage: opencvgrpc
  target_stage: lang_sam
  pipeline: architecture_pipeline
---
kind: link
spec:
  name: acquire_vggt-vggt
  source_stage: acquire_vggt
  target_stage: vggtgrpc
  pipeline: architecture_pipeline
---
kind: link
spec:
  name: lang_sam-display
  source_stage: lang_sam
  target_stage: display_langsam
  pipeline: architecture_pipeline
---
kind: link
spec:
  name: yolo-display
  source_stage: yolo
  target_stage: display_yolo
  pipeline: architecture_pipeline
---
kind: link
spec:
  name: vggt-display
  source_stage: vggtgrpc
  target_stage: display_vggt
  pipeline: architecture_pipeline
