services:
  folder_wdgrpc:
    image: sipgisr/folder_wdgrpc
    environment:
      - INPUT_FOLDER=/data
      - OUTPUT_FOLDER=/data/output
    networks:
      - mynet
    volumes:
      - ../../folder_wd/test/:/data:rw

  opencvgrpc:
    image: sipgisr/opencvgrpc
    networks:
      - mynet

  lang_samgrpc:
    image: sipgisr/lang_samgrpc
    volumes:
      - ../../lang_segm/:/workspace:rw
    entrypoint: ["python3", "/workspace/src/lang_sam_service.py"]
    user: "root"
    networks:
      - mynet

  yologrpc:
    image: sipgisr/yologrpc
    networks:
      - mynet
      
  maestro:
    image: sipgisr/maestro:v1-latest
    volumes:
      - type: bind
        source: ./config.yaml
        target: /config.yaml
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 173.29.0.0/16
