services:
  folder_wdgrpc:
    image: sipgisr/folder_wdgrpc
    environment:
      - INPUT_FOLDER=/data
      - OUTPUT_FOLDER=/data/output
    networks:
      - mynet
    volumes:
      - ../../folder_wd/test/:/data:rw

  lang_samgrpc:
    image: sipgisr/lang_samgrpc
    volumes:
      - ../../lang_segm/:/workspace:rw
    networks:
      - mynet
    user: "root"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  opencvgrpc:
    image: sipgisr/opencvgrpc
    networks:
      - mynet

  yologrpc:
    image: sipgisr/yologrpc
    networks:
      - mynet

  vggtgrpc:
    image: sipgisr/vggt_newgrpc
    networks:
      - mynet
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
      
  maestro:
    image: sipgisr/maestro:v1-latest
    volumes:
      - type: bind
        source: ./config.yaml
        target: /config.yaml
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 173.29.0.0/16
