kind: pipeline
spec:
  name: VGGT
---
kind: stage
spec:
  name: vggtgrpc
  method: Process
  address: vggtgrpc:8061
  pipeline: VGGT
---
kind: stage
spec: 
  name: gradio-source
  method: acquire
  address: interface:8061
  pipeline: VGGT
---
kind: stage
spec: 
  name: gradio-display
  method: display
  address: interface:8061
  pipeline: VGGT
---
kind: link
spec:
  name: vggt-gradio
  source_stage: vggtgrpc
  target_stage: gradio-display
  pipeline: VGGT
---
kind: link
spec:
  name: gradio-vggt
  source_stage: gradio-source
  target_stage: vggtgrpc
  pipeline: VGGT
