# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pipeline_pb2 as pipeline__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pipeline_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DisplayServiceStub(object):
    """Universal service interface
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.display = channel.unary_unary(
                '/pipeline.DisplayService/display',
                request_serializer=pipeline__pb2.Envelope.SerializeToString,
                response_deserializer=pipeline__pb2.Envelope.FromString,
                _registered_method=True)
        self.acquire = channel.unary_unary(
                '/pipeline.DisplayService/acquire',
                request_serializer=pipeline__pb2.Envelope.SerializeToString,
                response_deserializer=pipeline__pb2.Envelope.FromString,
                _registered_method=True)


class DisplayServiceServicer(object):
    """Universal service interface
    """

    def display(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def acquire(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DisplayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'display': grpc.unary_unary_rpc_method_handler(
                    servicer.display,
                    request_deserializer=pipeline__pb2.Envelope.FromString,
                    response_serializer=pipeline__pb2.Envelope.SerializeToString,
            ),
            'acquire': grpc.unary_unary_rpc_method_handler(
                    servicer.acquire,
                    request_deserializer=pipeline__pb2.Envelope.FromString,
                    response_serializer=pipeline__pb2.Envelope.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pipeline.DisplayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pipeline.DisplayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DisplayService(object):
    """Universal service interface
    """

    @staticmethod
    def display(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipeline.DisplayService/display',
            pipeline__pb2.Envelope.SerializeToString,
            pipeline__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def acquire(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipeline.DisplayService/acquire',
            pipeline__pb2.Envelope.SerializeToString,
            pipeline__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
