kind: pipeline
spec:
  name: Yolo
---
kind: stage
spec:
  name: Yolodetect
  method: AllProcessing
  address: yologrpc:8061
  pipeline: Yolo
---
kind: stage
spec: 
  name: gradio-source
  method: acquire
  address: interface:8061
  pipeline: Yolo
---
kind: stage
spec: 
  name: gradio-display
  method: display
  address: interface:8061
  pipeline: Yolo
---
kind: link
spec:
  name: yolo-gradio
  source_stage: Yolodetect
  target_stage: gradio-display
  pipeline: Yolo
---
kind: link
spec:
  name: gradio-yolo
  source_stage: gradio-source
  target_stage: Yolodetect
  pipeline: Yolo
