services:
  interface:
    image: sipgisr/gradio_display_multiple
    ports:
    - 7860:7860
  yologpt:
    image: sipgisr/yolov11
    ports:
    - 8062:8061
  maestro:
    image: duartemralves/maestro:v1-latest
    volumes:
      - type: bind
        source: ./config.yaml
        target: /config.yaml
