services:
  interface:
    image: sipgisr/displaygrpc
    ports:
      - 7860:7860   # Only expose if you want access from host
    networks:
      - mynet

  yologrpc:
    image: sipgisr/yologrpc
    networks:
      - mynet

  maestro:
    image: sipgisr/maestro:v1-latest
    volumes:
      - type: bind
        source: ./config.yaml
        target: /config.yaml
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
    internal: true