version: '3'
services:
  interface:
    image: sipgisr/acquisition
    ports:
    - 7860:7860
  yologpt:
    image: sipgisr/yolov11
  orchestrator-node:
    image: sipgisr/grpc-orchestrator:latest
    volumes: 
    - type: bind
      source: ./Config
      target: /app/config
    environment:
      CONFIG_FILE: "config/config.yaml"
    command: bash -c "/usr/bin/wait-for-all.sh config/urls.txt && java -cp '*' pipeline.orchestrator.App"
    