# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sbert.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'sbert.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bsbert.proto\"!\n\x0cSBERTRequest\x12\x11\n\tsentences\x18\x01 \x03(\t\"9\n\rSBERTResponse\x12\x12\n\nembeddings\x18\x01 \x01(\x0c\x12\x14\n\x0csimilarities\x18\x02 \x01(\x0c\x32\x38\n\x0cSBERTService\x12(\n\x07\x46orward\x12\r.SBERTRequest\x1a\x0e.SBERTResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sbert_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SBERTREQUEST']._serialized_start=15
  _globals['_SBERTREQUEST']._serialized_end=48
  _globals['_SBERTRESPONSE']._serialized_start=50
  _globals['_SBERTRESPONSE']._serialized_end=107
  _globals['_SBERTSERVICE']._serialized_start=109
  _globals['_SBERTSERVICE']._serialized_end=165
# @@protoc_insertion_point(module_scope)
