# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vggt.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'vggt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nvggt.proto\"H\n\x0bVGGTRequest\x12\x0e\n\x06images\x18\x01 \x03(\x0c\x12\x14\n\x0cquery_points\x18\x02 \x01(\x0c\x12\x13\n\x0b\x63onfig_json\x18\x03 \x01(\t\"\xae\x01\n\x0cVGGTResponse\x12\x10\n\x08pose_enc\x18\x01 \x01(\x0c\x12\r\n\x05\x64\x65pth\x18\x02 \x01(\x0c\x12\x12\n\ndepth_conf\x18\x03 \x01(\x0c\x12\x14\n\x0cworld_points\x18\x04 \x01(\x0c\x12\x19\n\x11world_points_conf\x18\x05 \x01(\x0c\x12\x0e\n\x06images\x18\x06 \x01(\x0c\x12\r\n\x05track\x18\x07 \x01(\x0c\x12\x0b\n\x03vis\x18\x08 \x01(\x0c\x12\x0c\n\x04\x63onf\x18\t \x01(\x0c\x32\x35\n\x0bVGGTService\x12&\n\x07\x46orward\x12\x0c.VGGTRequest\x1a\r.VGGTResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vggt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VGGTREQUEST']._serialized_start=14
  _globals['_VGGTREQUEST']._serialized_end=86
  _globals['_VGGTRESPONSE']._serialized_start=89
  _globals['_VGGTRESPONSE']._serialized_end=263
  _globals['_VGGTSERVICE']._serialized_start=265
  _globals['_VGGTSERVICE']._serialized_end=318
# @@protoc_insertion_point(module_scope)
