# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cotracker.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'cotracker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63otracker.proto\"`\n\x10\x43oTrackerRequest\x12\r\n\x05video\x18\x01 \x01(\x0c\x12\x14\n\x0cvideo_tensor\x18\x02 \x01(\x0c\x12\x14\n\x0cquery_points\x18\x03 \x01(\x0c\x12\x11\n\tgrid_size\x18\x04 \x01(\x05\"#\n\x11\x43oTrackerResponse\x12\x0e\n\x06tracks\x18\x01 \x01(\x0c\x32\x44\n\x10\x43oTrackerService\x12\x30\n\x07\x46orward\x12\x11.CoTrackerRequest\x1a\x12.CoTrackerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cotracker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COTRACKERREQUEST']._serialized_start=19
  _globals['_COTRACKERREQUEST']._serialized_end=115
  _globals['_COTRACKERRESPONSE']._serialized_start=117
  _globals['_COTRACKERRESPONSE']._serialized_end=152
  _globals['_COTRACKERSERVICE']._serialized_start=154
  _globals['_COTRACKERSERVICE']._serialized_end=222
# @@protoc_insertion_point(module_scope)
