# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import simplebox_pb2 as simplebox__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in simplebox_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SimpleBoxServiceStub(object):
    """
    Service that receives an image, applies some
    transformation to it and returns the new image
    :param Image: The image to process
    :returns: The transformed image
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.process = channel.unary_unary(
                '/SimpleBoxService/process',
                request_serializer=simplebox__pb2.matfile.SerializeToString,
                response_deserializer=simplebox__pb2.matfile.FromString,
                _registered_method=True)


class SimpleBoxServiceServicer(object):
    """
    Service that receives an image, applies some
    transformation to it and returns the new image
    :param Image: The image to process
    :returns: The transformed image
    """

    def process(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimpleBoxServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'process': grpc.unary_unary_rpc_method_handler(
                    servicer.process,
                    request_deserializer=simplebox__pb2.matfile.FromString,
                    response_serializer=simplebox__pb2.matfile.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SimpleBoxService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('SimpleBoxService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SimpleBoxService(object):
    """
    Service that receives an image, applies some
    transformation to it and returns the new image
    :param Image: The image to process
    :returns: The transformed image
    """

    @staticmethod
    def process(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SimpleBoxService/process',
            simplebox__pb2.matfile.SerializeToString,
            simplebox__pb2.matfile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
