# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: clip.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'clip.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nclip.proto\",\n\x0b\x43LIPRequest\x12\x0e\n\x06images\x18\x01 \x03(\x0c\x12\r\n\x05texts\x18\x02 \x03(\t\"G\n\x0c\x43LIPResponse\x12\x11\n\timage_emb\x18\x01 \x01(\x0c\x12\x10\n\x08text_emb\x18\x02 \x01(\x0c\x12\x12\n\nsimilarity\x18\x03 \x01(\x0c\x32\x35\n\x0b\x43LIPService\x12&\n\x07\x46orward\x12\x0c.CLIPRequest\x1a\r.CLIPResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clip_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIPREQUEST']._serialized_start=14
  _globals['_CLIPREQUEST']._serialized_end=58
  _globals['_CLIPRESPONSE']._serialized_start=60
  _globals['_CLIPRESPONSE']._serialized_end=131
  _globals['_CLIPSERVICE']._serialized_start=133
  _globals['_CLIPSERVICE']._serialized_end=186
# @@protoc_insertion_point(module_scope)
